### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by willcbaker** [swift-nav/swiftnav-ros2#38]
Unable to build `master` on humble following instructions from:
https://github.com/swift-nav/swiftnav-ros2/blob/master/docs/build-in-docker.md

Seems the regression was introduced in #35 

Looks like it even fails in the github actiosn too
https://github.com/swift-nav/swiftnav-ros2/actions/runs/4864865903/jobs/8674433304#step:3:2512

**Comment by silverjam** [comment]
This should be resolved by #39 -- thanks for reporting.
