### ISSUE TITLE
Multiple receiver support

### ISSUE THREAD

**Issue by JTaveau** [swift-nav/swiftnav-ros2#41]
Hi, is the current sbp-to-ros driver supporting multiple receivers as [this node](https://github.com/swift-nav/ethz_piksi_ros/blob/master/piksi_multi_cpp/src/piksi_multi_node.cc) was doing on ROS1?

**Comment by switanis** [comment]
Hi, the driver itself supports one receiver but you may run multiple instances of the driver.
